### ISSUE TITLE
De un punto en el mapa, encontrar su distrito, sección electoral, y AGEB

### ISSUE THREAD

**Issue by rodowi** [civica-digital/sociedad-actua#81]
Para sacar información electoral de una coordenada
```sql
SELECT municipio, distrito, seccion
FROM public.nl_secciones_electorales
WHERE ST_Within(ST_GeomFromText('POINT(-100.30860900878906 25.686706571891094)', 4326), the_geom)
```
_reemplazar los valores de longitud y latitud_

API call:
https://cicadmin.cartodb.com:443/api/v2/sql?q=select municipio, distrito, seccion from public.nl_secciones_electorales where ST_Within(ST_GeomFromText('POINT(-100.30860900878906 25.686706571891094)', 4326), the_geom)

**Comment by rodowi** [comment]
Para sacar el AGEB de una coordenada

```sql
SELECT cvegeo 
FROM nl_ageb_urb 
WHERE ST_Within(ST_GeomFromText('POINT(-100.30860900878906 25.686706571891094)', 4326), the_geom)
```
_reemplazar los valores de longitud y latitud_

API call
https://jpel.cartodb.com/api/v2/sql?q=SELECT cvegeo FROM nl_ageb_urb WHERE ST_Within(ST_GeomFromText('POINT(-100.30860900878906 25.686706571891094)', 4326), the_geom)

**Comment by juanpabloe** [comment]
:muscle:
